export type ClubSeed = {
  slug: string;
  name: string;
  description: string;
  focus: string;
  color: string;
  icon: string;
  websiteUrl?: string;
  contactEmail?: string;
  logoUrl?: string;
  facultyCoordinator?: string;
  studentCoordinator?: string;
  category?: string;
};

export const CLUB_SEED: ClubSeed[] = [
  {
    slug: "coding-club",
    name: "Coding Club",
    description: "Build product-minded engineers through collaborative software projects.",
    focus: "Product development",
    color: "Stone",
    icon: "</>",
    websiteUrl: "https://codingclub.college.edu",
    contactEmail: "codingclub@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=400",
    facultyCoordinator: "Dr. Rajesh Kumar (CSE)",
    studentCoordinator: "Aditya Sharma",
    category: "Technical",
  },
  {
    slug: "robotics-club",
    name: "Robotics Club",
    description: "Design intelligent machines, automation demos, and hardware showcases.",
    focus: "Automation and hardware",
    color: "Graphite",
    icon: "◎",
    websiteUrl: "https://robotics.college.edu",
    contactEmail: "robotics@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=400",
    facultyCoordinator: "Dr. Amit Verma (ECE)",
    studentCoordinator: "Neha Gupta",
    category: "Technical",
  },
  {
    slug: "debate-society",
    name: "Debate Society",
    description: "Sharpen structured thinking, public speaking, and policy analysis.",
    focus: "Communication",
    color: "Ink",
    icon: "✦",
    websiteUrl: "https://debate.college.edu",
    contactEmail: "debate@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=400",
    facultyCoordinator: "Prof. Sudha Murthy (Humanities)",
    studentCoordinator: "Rohan Das",
    category: "Literary",
  },
  {
    slug: "literary-club",
    name: "Literary Club",
    description: "Host readings, writing circles, and storytelling workshops.",
    focus: "Creative writing",
    color: "Paper",
    icon: "✎",
    websiteUrl: "https://litclub.college.edu",
    contactEmail: "literary@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?q=80&w=400",
    facultyCoordinator: "Dr. Anil K. Joseph (English)",
    studentCoordinator: "Anjali Menon",
    category: "Literary",
  },
  {
    slug: "music-club",
    name: "Music Club",
    description: "Support rehearsals, showcases, and student-led performances.",
    focus: "Performance arts",
    color: "Charcoal",
    icon: "♫",
    websiteUrl: "https://music.college.edu",
    contactEmail: "music@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=400",
    facultyCoordinator: "Prof. Meera Sen (Arts)",
    studentCoordinator: "Vikram Malhotra",
    category: "Cultural",
  },
  {
    slug: "dance-club",
    name: "Dance Club",
    description: "Coordinate choreography sessions, showcases, and community performances.",
    focus: "Movement and stagecraft",
    color: "Slate",
    icon: "◌",
    websiteUrl: "https://dance.college.edu",
    contactEmail: "dance@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=400",
    facultyCoordinator: "Dr. Shweta Iyer (Arts)",
    studentCoordinator: "Pooja Hegde",
    category: "Cultural",
  },
  {
    slug: "photography-club",
    name: "Photography Club",
    description: "Document campus life through photo walks, edits, and exhibitions.",
    focus: "Visual storytelling",
    color: "Ash",
    icon: "◫",
    websiteUrl: "https://photography.college.edu",
    contactEmail: "photo@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=400",
    facultyCoordinator: "Prof. K. L. James (Media)",
    studentCoordinator: "Siddharth Sen",
    category: "Cultural",
  },
  {
    slug: "entrepreneurship-club",
    name: "Entrepreneurship Club",
    description: "Turn student ideas into startup-ready plans and pitch sessions.",
    focus: "Innovation",
    color: "Graphite",
    icon: "◈",
    websiteUrl: "https://eclub.college.edu",
    contactEmail: "eclub@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400",
    facultyCoordinator: "Dr. R. C. Mashelkar (Management)",
    studentCoordinator: "Karan Bajaj",
    category: "Technical",
  },
  {
    slug: "environment-club",
    name: "Environment Club",
    description: "Lead sustainability campaigns, recycling drives, and awareness programs.",
    focus: "Sustainability",
    color: "Olive",
    icon: "❋",
    websiteUrl: "https://eco.college.edu",
    contactEmail: "ecoclub@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=400",
    facultyCoordinator: "Dr. Vandana Shiva (Environmental Sci)",
    studentCoordinator: "Gita Gopinath",
    category: "Social Service",
  },
  {
    slug: "sports-club",
    name: "Sports Club",
    description: "Manage training schedules, inter-college fixtures, and fitness events.",
    focus: "Athletics",
    color: "Steel",
    icon: "◐",
    websiteUrl: "https://sports.college.edu",
    contactEmail: "sports@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=400",
    facultyCoordinator: "Coach Balbir Singh (Physical Edu)",
    studentCoordinator: "Arjun Pal",
    category: "Sports",
  },
  {
    slug: "volunteer-club",
    name: "Volunteer Club",
    description: "Organize service drives, outreach programs, and impact reporting.",
    focus: "Community service",
    color: "Graphite",
    icon: "✿",
    websiteUrl: "https://volunteer.college.edu",
    contactEmail: "volunteer@college.edu",
    logoUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=400",
    facultyCoordinator: "Prof. Kiran Bedi (Social Work)",
    studentCoordinator: "Kabir Khan",
    category: "Social Service",
  },
];
